import {
  ArrowPathIcon,
  MusicalNoteIcon,
  UserIcon,
  EnvelopeIcon,
  LockClosedIcon,
  MapPinIcon,
  PhoneIcon,
  GlobeAltIcon,
  MicrophoneIcon,
  TagIcon,
  MusicalNoteIcon as FileAudioIcon,
  InformationCircleIcon,
  ClockIcon,
  TrophyIcon,
  StarIcon,
  TargetIcon,
  ChevronLeftIcon,
  WaveformIcon,
  ChartBarIcon,
  ChartBarIcon as LineChartIcon,
} from '@heroicons/react/24/outline'

export const Icons = {
  spinner: ArrowPathIcon,
  music: MusicalNoteIcon,
  user: UserIcon,
  mail: EnvelopeIcon,
  lock: LockClosedIcon,
  location: MapPinIcon,
  phone: PhoneIcon,
  website: GlobeAltIcon,
  microphone: MicrophoneIcon,
  genres: TagIcon,
  daw: FileAudioIcon,
  info: InformationCircleIcon,
  clock: ClockIcon,
  trophy: TrophyIcon,
  star: StarIcon,
  target: TargetIcon,
  chevronLeft: ChevronLeftIcon,
  waveform: WaveformIcon,
  barChart: ChartBarIcon,
  lineChart: LineChartIcon,
}
